# Generated by Django 4.0.1 on 2022-01-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='create',
            new_name='created',
        ),
    ]
