# Generated by Django 4.0.1 on 2022-01-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_create_projects_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='desciption',
            new_name='description',
        ),
    ]
