# Generated by Django 3.2.9 on 2022-01-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_desciption_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='stack1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='stack2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='stack3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='stack4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
