# Generated by Django 4.2.1 on 2023-05-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220129_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stacks/')),
            ],
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='sourcecodelink',
            new_name='source_code_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='stack1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='stack2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='stack3',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='stack4',
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='code.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='stacks',
            field=models.ManyToManyField(blank=True, null=True, to='api.stack'),
        ),
    ]
