# Generated by Django 4.2.1 on 2023-05-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stack_rename_created_projects_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='code.jpg', null=True, upload_to='projects/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('source_code_link', models.CharField(blank=True, max_length=200, null=True)),
                ('view_link', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stacks', models.ManyToManyField(blank=True, null=True, to='api.stack')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
