# Generated by Django 4.2.1 on 2023-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
