# Generated by Django 4.2.1 on 2023-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_project_short_desc_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
