# Generated by Django 4.2.1 on 2023-05-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
