# Generated by Django 4.2.1 on 2023-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_project_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='projects/code.jpg', null=True, upload_to='projects/'),
        ),
    ]
